/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories/$slug' | '/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories/$slug' | '/tools/$slug'
  id: '__root__' | '/' | '/categories/$slug' | '/tools/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
